import Head from "next/head";
import AllPosts from "@/components/AllPosts";
import ToggleReload from "@/models/ToggleReload";

export default function Home(props: ToggleReload) {
  console.log(props.toggleReload);
  return (
    <>
      <Head>
        <title>Blog app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AllPosts toggleReload={props.toggleReload} />
    </>
  );
}
